mygtkapp: Test.c
			gcc -o Test Test.c `pkg-config --cflags --libs gtk+-3.0`


PROG = Test
CC = gcc
CFLAGS = 'pkg-config --cflags gtk+-3.0'
LIBS = 'pkg-config --libs gtk+-3.0'

${PROG} : ${PROG}.c
		 ${CC} ${CFLAGS} -o ${PROG} ${PROG}.c ${LIBS}
clean : 
		rm ${PROG}